### ISSUE TITLE
我换了一个微信的包 就出错了

### ISSUE THREAD

**Issue by hongdong** [codesourse/iInjection#1]
/var/folders/qg/xlkm15q93klg19261d061xn00000gn/T/com.DanTheMan827.AppSigner.Z2rrwcaX/out/Payload/WeChat.app: invalid or unsupported format for signature
In architecture: x86_64

**Comment by codesourse** [comment]
Your  binary file is encrypted,follows may help you.
http://www.jianshu.com/p/a4373b5feca0
