### ISSUE TITLE
重签名安装后闪退

### ISSUE THREAD

**Issue by wanghe826** [codesourse/iInjection#2]
非常感谢你开源的这个工具，请教一下为什么我用企业证书重新签名后安装进手机打开就闪退呢？  大概是什么原因造成的，怎样定位这个问题，谢谢！！

**Comment by codesourse** [comment]
你先看看，你的ipa 是否砸壳，没有越狱机子未砸壳可以去pp助手上下一个，还有5c 会闪退，最后检查代码是否有bug

**Comment by wanghe826** [comment]
嗯，结果发现是没有砸克的原因，非常感谢！！！
